session_name: 'forwardgram' # Session name. Only one session (with a unique session name) can run at a time

phone: '972549105922'
telegram_password: Ronitovd12

# The channel names that you'd like to forward messages from.
# The user running the client must have these channels present on it's dialogs.
input_channel_names:
  # - 'ğŸ¯Crypto snipersğŸ¯'
  # - 'ronh channel'
  # - 'CryptoSnipersVIPTest'
  - 'CryptoSnipersVIP'
  - 'VIP CLUB'
  # - 'VIP | Binance Master'

# The output channel names that the messages will be forwarded to.
# The user running the client must have a write access to those channels, and have the channels present on theirs dialogs.
output_channel_names: 
  - 'â­ï¸TopSignalsâ­ï¸'
  # - 'â­ï¸TopSignalsTestâ­ï¸'

# The channel IDs that you'd like to forward messages from. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
input_channel_ids:
  # - -1001722157175 # ğŸ¯Crypto snipersğŸ¯
  # - -1001683787338 # ronh channel
  - -1001560182023 # CryptoSnipersVIP
  - -1001756092613 # VIP CLUB
  # - 2083418232 # VIP | Binance Master

# The output channel IDs that the messages will be forwarded to. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
output_channel_ids: 
  - -1001738452085 # â­ï¸TopSignalsâ­ï¸'

# An empty list should be set like this: 
# input_channel_ids: []